/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HabitsIndexRouteImport } from './routes/habits/index'
import { Route as HabitsNewRouteImport } from './routes/habits/new'
import { Route as HabitsHabitIdIndexRouteImport } from './routes/habits/$habitId/index'
import { Route as HabitsHabitIdEditRouteImport } from './routes/habits/$habitId/edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsNewRoute = HabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHabitIdIndexRoute = HabitsHabitIdIndexRouteImport.update({
  id: '/habits/$habitId/',
  path: '/habits/$habitId/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHabitIdEditRoute = HabitsHabitIdEditRouteImport.update({
  id: '/habits/$habitId/edit',
  path: '/habits/$habitId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/habits/new': typeof HabitsNewRoute
  '/habits/': typeof HabitsIndexRoute
  '/habits/$habitId/edit': typeof HabitsHabitIdEditRoute
  '/habits/$habitId/': typeof HabitsHabitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/habits/new': typeof HabitsNewRoute
  '/habits': typeof HabitsIndexRoute
  '/habits/$habitId/edit': typeof HabitsHabitIdEditRoute
  '/habits/$habitId': typeof HabitsHabitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/habits/new': typeof HabitsNewRoute
  '/habits/': typeof HabitsIndexRoute
  '/habits/$habitId/edit': typeof HabitsHabitIdEditRoute
  '/habits/$habitId/': typeof HabitsHabitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/habits/new'
    | '/habits/'
    | '/habits/$habitId/edit'
    | '/habits/$habitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/habits/new'
    | '/habits'
    | '/habits/$habitId/edit'
    | '/habits/$habitId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/habits/new'
    | '/habits/'
    | '/habits/$habitId/edit'
    | '/habits/$habitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HabitsNewRoute: typeof HabitsNewRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  HabitsHabitIdEditRoute: typeof HabitsHabitIdEditRoute
  HabitsHabitIdIndexRoute: typeof HabitsHabitIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/new': {
      id: '/habits/new'
      path: '/habits/new'
      fullPath: '/habits/new'
      preLoaderRoute: typeof HabitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$habitId/': {
      id: '/habits/$habitId/'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId/'
      preLoaderRoute: typeof HabitsHabitIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$habitId/edit': {
      id: '/habits/$habitId/edit'
      path: '/habits/$habitId/edit'
      fullPath: '/habits/$habitId/edit'
      preLoaderRoute: typeof HabitsHabitIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HabitsNewRoute: HabitsNewRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  HabitsHabitIdEditRoute: HabitsHabitIdEditRoute,
  HabitsHabitIdIndexRoute: HabitsHabitIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
